<?php

namespace App\Http\Requests\Api;

//use Illuminate\Foundation\Http\FormRequest;
use Dingo\Api\Http\FormRequest;
class BedPost extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            "bed_num"=>"required|numeric",
            "general_seat"=>"required|numeric",
            "icu_seat"=>"required|numeric",
        ];
    }

    public function messages()
    {
        //   return parent::messages(); // TODO: Change the autogenerated stub
        return [
            "bed_num.required"=>"请输入总床位数",
            "bed_num.numeric"=>"总床位数只能是数值",
            "general_seat.required"=>"请输入普通床位数",
            "general_seat.numeric"=>"普通床位数只能是数值",
            "icu_seat.required"=>"请输入icu床位数",
            "icu_seat.numeric"=>"icu床位数只能是数值",
        ];
    }
}
