<?php

namespace App\Http\Requests\Api;

use Illuminate\Foundation\Http\FormRequest;

class ForgotpwdRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            "mobile"=>[
                "required",
                "regex:/^((13[0-9])|(14[5,7])|(15[0-3,5-9])|(17[0,3,5-8])|(18[0-9])|166|198|199|(147))\d{8}$/",
            ],
            "code"=>"required",
            "password"=>"required|min:6|confirmed:password",
            "password_confirmation"=>"required",
        ];
    }

    public function messages()
    {
        //   return parent::messages(); // TODO: Change the autogenerated stub
        return [
            "mobile.required"=>"请输入手机号码",
            "mobile.regex"=>"手机号码格式错误",
            "code.required"=>"请输入验证码",
            "password.required"=>"请输入登录密码",
            "password.min"=>"新密码最少6位",
            "password_confirmation.required"=>"请输入确认密码",
            "password.confirmed"=>"确认密码和登录密码不一致"
        ];
    }
}
