<?php

namespace App\Http\Requests\Api;

//use Illuminate\Foundation\Http\FormRequest;
use Dingo\Api\Http\FormRequest;
class ResetpwdRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'oldpassword'=>'required|min:6',
            "password"=>"required|min:6|confirmed:password",
            "password_confirmation"=>"required",
        ];
    }

    public function messages()
    {
        //   return parent::messages(); // TODO: Change the autogenerated stub
        return [
            "oldpassword.required"=>"请输入原密码",
            "oldpassword.min"=>"密码最少6位",

            "password.required"=>"请输入密码",
            "password.min"=>"新密码最少6位",
            "password_confirmation.required"=>"请输入确认密码",
            "password.confirmed"=>"确认密码和密码不一致"
        ];
    }
}
