<?php

namespace App\Http\Requests\Api;

//use Illuminate\Foundation\Http\FormRequest;
use Dingo\Api\Http\FormRequest;
class UserProfileRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            "username"=>"required",
            "hospitalid"=>"required",
            "bed_num"=>"required|numeric",
            "subjectid"=>"required",
            "skillid"=>"required",
            "positionid"=>"required",
            "introduction"=>"required"
        ];
    }
    public function messages()
    {
        //   return parent::messages(); // TODO: Change the autogenerated stub
        return [
            "username.required"=>"请填写姓名",
            "hospitalid.required"=>"请选择医院",
            "bed_num.required"=>"请填写床位数",
            "bed_num.numeric"=>"床位数只能是数值",
            "subjectid.required"=>"请选择科室",
            "skillid.required"=>"请选择专业特长",
            "positionid.required"=>"请选择职位",
            "introduction.required"=>"请填写个人简介",
        ];
    }
}
