<?php

namespace App\Http\Requests\Home;

use Illuminate\Foundation\Http\FormRequest;

class ReferraPost extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            "name"=>"required",
            "mobile"=>[
                "required",
                "regex:/^((13[0-9])|(14[5,7])|(15[0-3,5-9])|(17[0,3,5-8])|(18[0-9])|166|198|199|(147))\d{8}$/"
            ],
            "description"=>"required",
            "ill_desc"=>"required",
            "ill_breath"=>"required",
            "ill_room"=>"required",
            "ill_transfer"=>"required",
            "ill_ntime"=>"required",
        ];
    }

    public function messages()
    {
     //   return parent::messages(); // TODO: Change the autogenerated stub
        return [
            "name.required"=>"请填写患者姓名",
            "mobile.required"=>"请填写患者手机号",
            "mobile.regex"=>"手机号填写错误",
            "description.required"=>"请填写病情描述",
            "ill_desc.required"=>"请填写患者病情",
            "ill_breath.required"=>"请填写呼吸支持",
            "ill_room.required"=>"请填写病房需求",
            "ill_transfer.required"=>"请填写转运需求",
            "ill_ntime.required"=>"请填写时间需求",
        ];
    }
}
