<?php

namespace App\Http\Requests\Home;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class UserPosts extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules(Request $request)
    {
        //'regex:/^((13[0-9])|(14[5,7])|(15[0-3,5-9])|(17[0,3,5-8])|(18[0-9])|166|198|199|(147))\d{8}$/',
        //                'unique:users'
        return [
            //
            //"mobile"=>"required|regex:/^((13[0-9])|(14[5,7])|(15[0-3,5-9])|(17[0,3,5-8])|(18[0-9])|166|198|199|(147))\d{8}$/|unique:users",
            "mobile"=>[
                "required",
                "regex:/^((13[0-9])|(14[5,7])|(15[0-3,5-9])|(17[0,3,5-8])|(18[0-9])|166|198|199|(147))\d{8}$/",
                "unique:users"
            ],
            "code"=>"required",
            "provinceid"=>"required",
            "hospitalid"=>[
                "required",
                Rule::exists('hospital')->where(function ($query)use($request) {
                    $query->where('id', $request->hospitalid);
                }),
            ],
            "hospitalid"=>"required",
            "hospital_code"=>"required",
            "password"=>"required|min:6|confirmed:password",
            "password_confirmation"=>"required",

        ];
    }

    public function messages()
    {
        //return parent::messages(); // TODO: Change the autogenerated stub
        return [
            "mobile.required"=>"手机号必须填写",
            "mobile.regex"=>"手机号格式不正确",
            "mobile.unique"=>"该手机号已经注册",
            "code.required"=>"请填写验证码",
            "provinceid.required"=>"请选择地区",
            "hospitalid.required"=>"请选择医院",
            "hospitalid.exist"=>"选择的医院不存在",
            "hospital_code.required"=>"请填写医院代码",
            "password.required"=>"请输入密码",
            "password_confirmation.required"=>"请输入确认密码",
            "password.confirmed"=>"确认密码和密码不一致"
        ];
    }
}
